name: shady
description: Making it easier to work with GLSL shaders in Flutter.
version: 3.0.0
repository: https://bitbucket.org/Feenposhleen/shady

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  vector_math: ^2.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0